#!/usr/bin/env python3
"""
06_pairwise_correlation_analysis.py

Standalone pairwise correlation-analysis script for the cleaned target-specific CSV workflow.

What this script does:
- Loads one target-specific cleaned dataset CSV.
- Builds an explicit sample-by-sample table first: one row from the CSV becomes one row in the analysis table.
- Saves both all-row and pairwise-complete sorted sample tables before/alongside the statistical outputs.
- Lets you select FEATURE_1 and FEATURE_2 directly in this file.
- Allows every CSV column to be selected, including class/label columns.
- Converts selected columns into analysis-ready numeric vectors:
    * numeric / boolean columns are converted directly
    * string/object/category columns are encoded as category codes
- Computes a detailed pairwise relationship analysis:
    * Pearson correlation
    * Spearman rank correlation
    * Kendall rank correlation
    * simple linear regression y = intercept + slope * x
    * R², adjusted R², RMSE, MAE, residual standard error
    * residual summary and outlier counts
    * optional bootstrap confidence interval for slope/intercept/R²
- Saves several plots in both PNG and EPS:
    * scatter + linear fit
    * scatter + linear fit with binned means
    * residuals vs fitted values
    * residual histogram
    * Q-Q plot of residuals
    * observed vs fitted values
    * hexbin density plot
    * rank-rank scatter plot
- Writes a human-readable TXT report.
- Writes a machine-readable JSON summary.
- Saves all outputs into a folder named after the selected feature pair.

Run:
  python 06_pairwise_correlation_analysis.py

Adjust all parameters in the CONFIG section below.
No argument parsing is used.
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

try:
    from scipy import stats
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "This script requires scipy for correlation tests and Q-Q plots.\n"
        "Install it with: pip install scipy"
    ) from exc


# =============================================================================
# CONFIG (EDIT THESE)
# =============================================================================

# Target-specific cleaned dataset.
# This is the cleaned output generated by the previous cleaning script after TARGET selection.
# Examples from the pipeline:
#   data_isBugPresent_classification/cleaned_dataset.csv
#   data_isBugfix_classification/cleaned_dataset.csv
#   data_isSZZBugIntroducer_classification/cleaned_dataset.csv
#   OBJ_data_isBugPresent_risk_score/cleaned_dataset.csv
#   OBJ_data_isSZZBugIntroducer_risk_score/cleaned_dataset.csv
TARGET = "isSZZBugIntroducer"

# Choose the cleaned-data workflow folder suffix.
# Use "classification" for the classifier-cleaned dataset.
# Use "risk_score" for the risk-score/regressor-cleaned dataset.
CLEANED_DATA_KIND = "classification"

# Set True for the OBJ risk-score pipeline folders, e.g. OBJ_data_{TARGET}_risk_score.
# Set False for the regular folders, e.g. data_{TARGET}_classification.
USE_OBJ_PREFIX = False

if USE_OBJ_PREFIX:
    INPUT_CSV = Path(f"OBJ_data_{TARGET}_{CLEANED_DATA_KIND}") / "cleaned_dataset.csv"
else:
    INPUT_CSV = Path(f"data_{TARGET}_{CLEANED_DATA_KIND}") / "cleaned_dataset.csv"

# Select ANY two columns from the cleaned CSV.
# Class/label columns are allowed, e.g. "isBugPresent", "isBugfix", "isSZZBugIntroducer".
#FEATURE_1 = "dok0.004Avg"       # x-axis / predictor
#FEATURE_2 = "isBugPresent"      # y-axis / response

FEATURE_1 = "180fileHcpf"
FEATURE_2 = "180commitHcpf"

# Output root folder. The final folder will be:
#   OUTPUT_ROOT / "{FEATURE_1}_vs_{FEATURE_2}_correlation_analysis"
OUTPUT_ROOT = Path(f"correlation_analysis_results_{TARGET}_{CLEANED_DATA_KIND}")

# Existing project palette, kept in the same style as the post-hoc plotting scripts.
# custom_palette = ["#188FA7", "#769FB6", "#9DBBAE", "#D5D6AA", "#E2DBBE"] # orthogonal order
custom_palette = ["#188FA7", "#E2DBBE", "#769FB6", "#9DBBAE", "#D5D6AA"]

# Global font scaler for all plotting text.
FONT_SCALE = 1.0

# Data handling.
DROP_MISSING_PAIRWISE = True
MAX_CATEGORY_LEVELS_IN_REPORT = 50
LOW_VARIANCE_EPS = 1e-12

# Sample-by-sample export.
# Plain meaning:
# - Every CSV row is collected with FEATURE_1 and FEATURE_2 raw values and converted numeric values.
# - The complete table keeps all rows and marks whether both selected values are usable.
# - The sorted complete table keeps only rows usable for the correlation analysis.
SAVE_SAMPLEWISE_TABLES = True
SAMPLEWISE_SORT_BY: List[str] = ["x", "y", "original_row_index"]
SAMPLEWISE_SORT_ASCENDING: List[bool] = [True, True, True]
SAMPLEWISE_ADD_RANK_COLUMNS = True

# Optional row sampling for plots only. The statistical analysis still uses the full cleaned pairwise data.
# Use None to plot all rows. Set e.g. 20000 for large CSVs if the scatter plot is too heavy.
MAX_POINTS_FOR_SCATTER_PLOTS: Optional[int] = 50000
RANDOM_STATE = 42

# Binned means shown in one plot.
N_BINS = 20

# Bootstrap confidence intervals for linear-regression statistics.
RUN_BOOTSTRAP = True
BOOTSTRAP_ITERATIONS = 1000
BOOTSTRAP_CI = 0.95

# Plot export settings.
DPI = 300
SAVE_PNG = True
SAVE_EPS = True


# =============================================================================
# Plot style
# =============================================================================

plt.rcParams.update({
    "font.size": 12 * FONT_SCALE,
    "axes.titlesize": 20 * FONT_SCALE,
    "axes.labelsize": 18 * FONT_SCALE,
    "xtick.labelsize": 16 * FONT_SCALE,
    "ytick.labelsize": 16 * FONT_SCALE,
    "legend.fontsize": 14 * FONT_SCALE,
    "figure.titlesize": 20 * FONT_SCALE,
})

sns.set_theme(style="whitegrid")
# Re-apply rcParams after seaborn so FONT_SCALE remains in control.
plt.rcParams.update({
    "font.size": 12 * FONT_SCALE,
    "axes.titlesize": 20 * FONT_SCALE,
    "axes.labelsize": 18 * FONT_SCALE,
    "xtick.labelsize": 16 * FONT_SCALE,
    "ytick.labelsize": 16 * FONT_SCALE,
    "legend.fontsize": 14 * FONT_SCALE,
    "figure.titlesize": 20 * FONT_SCALE,
})


# =============================================================================
# Helpers
# =============================================================================

def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def safe_name(text: str) -> str:
    """Make column names safe for folders and filenames while preserving readability."""
    s = str(text).strip()
    s = re.sub(r"[^A-Za-z0-9._-]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "column"


def save_current_figure(out_dir: Path, stem: str) -> Dict[str, str]:
    paths: Dict[str, str] = {}
    if SAVE_PNG:
        png_path = out_dir / f"{stem}.png"
        plt.savefig(png_path, dpi=DPI, bbox_inches="tight")
        paths["png"] = str(png_path.resolve())
    if SAVE_EPS:
        eps_path = out_dir / f"{stem}.eps"
        plt.savefig(eps_path, format="eps", dpi=DPI, bbox_inches="tight")
        paths["eps"] = str(eps_path.resolve())
    plt.close()
    return paths


def dtype_kind(series: pd.Series) -> str:
    if pd.api.types.is_bool_dtype(series):
        return "boolean"
    if pd.api.types.is_numeric_dtype(series):
        return "numeric"
    if pd.api.types.is_datetime64_any_dtype(series):
        return "datetime"
    return "categorical_or_text"


def coerce_series_for_analysis(series: pd.Series, max_levels: int = MAX_CATEGORY_LEVELS_IN_REPORT) -> Tuple[pd.Series, Dict]:
    """
    Convert any selected CSV column into a numeric analysis vector.

    Plain meaning:
    - numeric columns stay numeric
    - bool columns become 0/1
    - datetime columns become seconds since epoch
    - object/string/category columns become deterministic category codes
    """
    original_dtype = str(series.dtype)
    kind = dtype_kind(series)
    info: Dict = {
        "column": series.name,
        "original_dtype": original_dtype,
        "conversion_kind": kind,
        "encoding": None,
        "num_unique_raw_non_missing": int(series.dropna().nunique()),
        "num_missing_raw": int(series.isna().sum()),
    }

    if kind == "boolean":
        out = series.astype("float64")
        info["encoding"] = "boolean converted to 0/1"
        return out, info

    if kind == "numeric":
        out = pd.to_numeric(series, errors="coerce")
        info["encoding"] = "numeric conversion with errors coerced to NaN"
        return out, info

    if kind == "datetime":
        dt = pd.to_datetime(series, errors="coerce")
        out = dt.astype("int64") / 1e9
        out = pd.Series(out, index=series.index, name=series.name).replace({-9223372036.854776: np.nan})
        info["encoding"] = "datetime converted to Unix seconds"
        return out, info

    # Try numeric first for object columns that contain numeric strings.
    numeric_try = pd.to_numeric(series, errors="coerce")
    non_missing = series.notna().sum()
    converted_non_missing = numeric_try.notna().sum()
    if non_missing > 0 and converted_non_missing / non_missing >= 0.95:
        info["conversion_kind"] = "numeric_string"
        info["encoding"] = "object/string parsed as numeric because >=95% of non-missing values were numeric"
        return numeric_try, info

    # Categorical/text fallback.
    cat = series.astype("string").fillna("<MISSING>").astype("category")
    out = pd.Series(cat.cat.codes.astype("float64"), index=series.index, name=series.name)
    levels = list(cat.cat.categories)
    mapping = {str(level): int(code) for code, level in enumerate(levels[:max_levels])}
    info["conversion_kind"] = "categorical_or_text_encoded"
    info["encoding"] = "category codes assigned by pandas category order; <MISSING> is explicit before pairwise dropping"
    info["num_category_levels"] = int(len(levels))
    info["category_code_mapping_first_levels"] = mapping
    if len(levels) > max_levels:
        info["category_mapping_truncated"] = True
        info["category_mapping_note"] = f"Only first {max_levels} levels included in report/JSON."
    else:
        info["category_mapping_truncated"] = False
    return out, info


def basic_summary(x: np.ndarray) -> Dict[str, float]:
    return {
        "n": int(len(x)),
        "mean": float(np.mean(x)),
        "std": float(np.std(x, ddof=1)) if len(x) > 1 else float("nan"),
        "min": float(np.min(x)),
        "q25": float(np.quantile(x, 0.25)),
        "median": float(np.median(x)),
        "q75": float(np.quantile(x, 0.75)),
        "max": float(np.max(x)),
    }


def corr_with_pvalues(x: np.ndarray, y: np.ndarray) -> Dict[str, Dict[str, float]]:
    out: Dict[str, Dict[str, float]] = {}
    pearson = stats.pearsonr(x, y)
    spearman = stats.spearmanr(x, y, nan_policy="omit")
    kendall = stats.kendalltau(x, y, nan_policy="omit")
    out["pearson"] = {"r": float(pearson.statistic), "p_value": float(pearson.pvalue)}
    out["spearman"] = {"rho": float(spearman.statistic), "p_value": float(spearman.pvalue)}
    out["kendall"] = {"tau": float(kendall.statistic), "p_value": float(kendall.pvalue)}
    return out


def linear_fit_metrics(x: np.ndarray, y: np.ndarray) -> Dict[str, float | List[float]]:
    n = len(x)
    slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)
    fitted = intercept + slope * x
    residuals = y - fitted
    sse = float(np.sum(residuals ** 2))
    mse = float(np.mean(residuals ** 2))
    rmse = float(math.sqrt(mse))
    mae = float(np.mean(np.abs(residuals)))
    y_var = float(np.sum((y - np.mean(y)) ** 2))
    r2 = float(1.0 - sse / y_var) if y_var > 0 else float("nan")
    adj_r2 = float(1.0 - (1.0 - r2) * (n - 1) / (n - 2)) if n > 2 and np.isfinite(r2) else float("nan")
    residual_se = float(math.sqrt(sse / (n - 2))) if n > 2 else float("nan")

    resid_std = float(np.std(residuals, ddof=1)) if n > 1 else float("nan")
    standardized_resid = residuals / resid_std if resid_std > 0 else np.full_like(residuals, np.nan)
    outlier_2sd = int(np.sum(np.abs(standardized_resid) > 2)) if resid_std > 0 else 0
    outlier_3sd = int(np.sum(np.abs(standardized_resid) > 3)) if resid_std > 0 else 0

    return {
        "n": int(n),
        "slope": float(slope),
        "intercept": float(intercept),
        "linear_regression_p_value_for_slope": float(p_value),
        "slope_std_error": float(std_err),
        "r_value": float(r_value),
        "r_squared": float(r2),
        "adjusted_r_squared": float(adj_r2),
        "rmse": rmse,
        "mae": mae,
        "sse": sse,
        "mse": mse,
        "residual_standard_error": residual_se,
        "residual_mean": float(np.mean(residuals)),
        "residual_std": resid_std,
        "residual_min": float(np.min(residuals)),
        "residual_q25": float(np.quantile(residuals, 0.25)),
        "residual_median": float(np.median(residuals)),
        "residual_q75": float(np.quantile(residuals, 0.75)),
        "residual_max": float(np.max(residuals)),
        "standardized_residuals_abs_gt_2": outlier_2sd,
        "standardized_residuals_abs_gt_3": outlier_3sd,
        "fitted_values": fitted.tolist(),
        "residuals": residuals.tolist(),
    }


def bootstrap_linear_ci(x: np.ndarray, y: np.ndarray, n_iter: int, ci: float, random_state: int) -> Dict[str, Dict[str, float]]:
    rng = np.random.default_rng(random_state)
    n = len(x)
    slopes: List[float] = []
    intercepts: List[float] = []
    r2s: List[float] = []

    for _ in range(n_iter):
        idx = rng.integers(0, n, size=n)
        xb = x[idx]
        yb = y[idx]
        if np.nanstd(xb) <= LOW_VARIANCE_EPS or np.nanstd(yb) <= LOW_VARIANCE_EPS:
            continue
        try:
            m = linear_fit_metrics(xb, yb)
        except Exception:
            continue
        slopes.append(float(m["slope"]))
        intercepts.append(float(m["intercept"]))
        r2s.append(float(m["r_squared"]))

    alpha = (1.0 - ci) / 2.0
    lo_q = alpha
    hi_q = 1.0 - alpha

    def q(vals: List[float]) -> Dict[str, float]:
        arr = np.asarray(vals, dtype=float)
        arr = arr[np.isfinite(arr)]
        if len(arr) == 0:
            return {"low": float("nan"), "high": float("nan"), "mean": float("nan"), "n_successful": 0}
        return {
            "low": float(np.quantile(arr, lo_q)),
            "high": float(np.quantile(arr, hi_q)),
            "mean": float(np.mean(arr)),
            "n_successful": int(len(arr)),
        }

    return {
        "ci_level": {"value": float(ci)},
        "slope": q(slopes),
        "intercept": q(intercepts),
        "r_squared": q(r2s),
    }


def prepare_analysis_dataframe(df: pd.DataFrame, feature_1: str, feature_2: str) -> Tuple[pd.DataFrame, pd.DataFrame, Dict, Dict]:
    """
    Build the row-wise pair table.

    Plain meaning:
    - One original CSV row is one sample.
    - For every sample, we collect FEATURE_1 and FEATURE_2 raw values.
    - We also store the converted numeric values x and y used by the analysis.
    - Then, only if DROP_MISSING_PAIRWISE=True, incomplete rows are removed from the
      statistical analysis table. The full sample-wise table is still saved separately.
    """
    if feature_1 not in df.columns:
        raise SystemExit(f"FEATURE_1 not found in CSV: {feature_1}\nAvailable columns include:\n" + "\n".join(df.columns[:100]))
    if feature_2 not in df.columns:
        raise SystemExit(f"FEATURE_2 not found in CSV: {feature_2}\nAvailable columns include:\n" + "\n".join(df.columns[:100]))

    x_num, x_info = coerce_series_for_analysis(df[feature_1])
    y_num, y_info = coerce_series_for_analysis(df[feature_2])

    # Explicit sample-by-sample collection. This is the central table: one row = one sample.
    samplewise_all = pd.DataFrame({
        "original_row_index": df.index.astype(int),
        "feature_1_name": feature_1,
        "feature_2_name": feature_2,
        "feature_1_raw": df[feature_1],
        "feature_2_raw": df[feature_2],
        "x": x_num,
        "y": y_num,
    })
    samplewise_all["pairwise_complete"] = samplewise_all["x"].notna() & samplewise_all["y"].notna()

    rows_before = len(samplewise_all)
    if DROP_MISSING_PAIRWISE:
        out = samplewise_all.loc[samplewise_all["pairwise_complete"]].copy()
    else:
        out = samplewise_all.copy()
    rows_after = len(out)

    x_info["rows_before_pairwise_drop"] = int(rows_before)
    x_info["rows_after_pairwise_drop"] = int(rows_after)
    y_info["rows_before_pairwise_drop"] = int(rows_before)
    y_info["rows_after_pairwise_drop"] = int(rows_after)

    return out, samplewise_all, x_info, y_info


def sort_samplewise_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Sort the sample-wise output using the configured columns."""
    sort_cols = [c for c in SAMPLEWISE_SORT_BY if c in df.columns]
    if not sort_cols:
        return df.copy()

    ascending = SAMPLEWISE_SORT_ASCENDING[:len(sort_cols)]
    if len(ascending) < len(sort_cols):
        ascending = ascending + [True] * (len(sort_cols) - len(ascending))

    return df.sort_values(sort_cols, ascending=ascending, kind="mergesort").reset_index(drop=True)


def add_samplewise_diagnostics(adf: pd.DataFrame, fit: Optional[Dict] = None) -> pd.DataFrame:
    """
    Add row-wise diagnostics to the complete sample table.

    Plain meaning:
    - rank_x and rank_y show the order of each sample after sorting/ranking.
    - fitted_y and residual are only available after the linear model was fitted.
    """
    out = adf.copy()

    if SAMPLEWISE_ADD_RANK_COLUMNS:
        out["rank_x"] = out["x"].rank(method="average")
        out["rank_y"] = out["y"].rank(method="average")

    if fit is not None:
        out["fitted_y"] = np.asarray(fit["fitted_values"], dtype=float)
        out["residual"] = np.asarray(fit["residuals"], dtype=float)
        resid_std = float(np.nanstd(out["residual"].to_numpy(dtype=float), ddof=1)) if len(out) > 1 else float("nan")
        if np.isfinite(resid_std) and resid_std > 0:
            out["standardized_residual"] = out["residual"] / resid_std
            out["abs_standardized_residual"] = out["standardized_residual"].abs()
        else:
            out["standardized_residual"] = np.nan
            out["abs_standardized_residual"] = np.nan

    return out


def save_samplewise_tables(
    out_dir: Path,
    pair_name: str,
    samplewise_all: pd.DataFrame,
    analysis_complete: pd.DataFrame,
) -> Dict[str, str]:
    """Save explicit sample-by-sample CSV files."""
    paths: Dict[str, str] = {}
    if not SAVE_SAMPLEWISE_TABLES:
        return paths

    samplewise_dir = out_dir / "samplewise_tables"
    ensure_dir(samplewise_dir)

    all_rows_path = samplewise_dir / f"{pair_name}_samplewise_all_rows.csv"
    samplewise_all_sorted = sort_samplewise_dataframe(samplewise_all)
    samplewise_all_sorted.to_csv(all_rows_path, index=False)
    paths["samplewise_all_rows_sorted_csv"] = str(all_rows_path.resolve())

    complete_path = samplewise_dir / f"{pair_name}_samplewise_pairwise_complete_sorted.csv"
    complete_sorted = sort_samplewise_dataframe(analysis_complete)
    complete_sorted.to_csv(complete_path, index=False)
    paths["samplewise_pairwise_complete_sorted_csv"] = str(complete_path.resolve())

    residual_sorted = analysis_complete.copy()
    if "abs_standardized_residual" in residual_sorted.columns:
        residual_sorted = residual_sorted.sort_values("abs_standardized_residual", ascending=False, kind="mergesort")
        residual_path = samplewise_dir / f"{pair_name}_samplewise_sorted_by_residual_outlier_strength.csv"
        residual_sorted.to_csv(residual_path, index=False)
        paths["samplewise_sorted_by_residual_outlier_strength_csv"] = str(residual_path.resolve())

    return paths

def sample_for_plot(adf: pd.DataFrame) -> pd.DataFrame:
    if MAX_POINTS_FOR_SCATTER_PLOTS is None or len(adf) <= MAX_POINTS_FOR_SCATTER_PLOTS:
        return adf
    return adf.sample(n=MAX_POINTS_FOR_SCATTER_PLOTS, random_state=RANDOM_STATE)


def add_regression_equation(ax, metrics: Dict[str, float], loc: str = "upper left") -> None:
    txt = (
        f"y = {metrics['intercept']:.4g} + {metrics['slope']:.4g} x\n"
        f"R² = {metrics['r_squared']:.4f}\n"
        f"RMSE = {metrics['rmse']:.4g}"
    )
    anchor = (0.03, 0.97) if loc == "upper left" else (0.97, 0.03)
    ha = "left" if loc == "upper left" else "right"
    va = "top" if loc == "upper left" else "bottom"
    ax.text(
        anchor[0], anchor[1], txt,
        transform=ax.transAxes,
        ha=ha,
        va=va,
        bbox=dict(facecolor="white", edgecolor="0.7", alpha=0.85),
        fontsize=12 * FONT_SCALE,
    )


def make_plots(adf: pd.DataFrame, out_dir: Path, feature_1: str, feature_2: str, metrics: Dict[str, float]) -> Dict[str, Dict[str, str]]:
    plot_paths: Dict[str, Dict[str, str]] = {}
    plot_df = sample_for_plot(adf)
    x = adf["x"].to_numpy(dtype=float)
    y = adf["y"].to_numpy(dtype=float)
    fitted = np.asarray(metrics["fitted_values"], dtype=float)
    residuals = np.asarray(metrics["residuals"], dtype=float)

    # 1) Scatter + linear fit.
    plt.figure(figsize=(10, 7))
    ax = sns.regplot(
        data=plot_df,
        x="x",
        y="y",
        scatter_kws={"s": 18, "alpha": 0.45, "color": custom_palette[0], "edgecolor": "none"},
        line_kws={"color": custom_palette[1], "linewidth": 2.5},
        ci=95,
    )
    ax.set_title(f"Linear relationship: {feature_1} vs {feature_2}")
    ax.set_xlabel(feature_1)
    ax.set_ylabel(feature_2)
    add_regression_equation(ax, metrics)
    plt.tight_layout()
    plot_paths["scatter_linear_fit"] = save_current_figure(out_dir, "01_scatter_linear_fit")

    # 2) Scatter + fit + binned means.
    tmp = adf[["x", "y"]].copy()
    tmp["bin"] = pd.qcut(tmp["x"], q=min(N_BINS, tmp["x"].nunique()), duplicates="drop")
    binned = tmp.groupby("bin", observed=True).agg(x_mean=("x", "mean"), y_mean=("y", "mean"), n=("y", "size")).reset_index()
    plt.figure(figsize=(10, 7))
    ax = plt.gca()
    ax.scatter(plot_df["x"], plot_df["y"], s=15, alpha=0.35, color=custom_palette[0], edgecolors="none", label="Rows")
    x_line = np.linspace(np.min(x), np.max(x), 200)
    y_line = metrics["intercept"] + metrics["slope"] * x_line
    ax.plot(x_line, y_line, color=custom_palette[1], linewidth=2.5, label="Linear fit")
    ax.plot(binned["x_mean"], binned["y_mean"], marker="o", color=custom_palette[2], linewidth=2.0, label="Binned means")
    ax.set_title(f"Linear fit with binned means: {feature_1} vs {feature_2}")
    ax.set_xlabel(feature_1)
    ax.set_ylabel(feature_2)
    ax.legend()
    add_regression_equation(ax, metrics)
    plt.tight_layout()
    plot_paths["scatter_fit_binned_means"] = save_current_figure(out_dir, "02_scatter_fit_binned_means")

    # 3) Residuals vs fitted.
    res_df = pd.DataFrame({"fitted": fitted, "residuals": residuals})
    res_plot_df = sample_for_plot(res_df)
    plt.figure(figsize=(10, 7))
    ax = plt.gca()
    ax.scatter(res_plot_df["fitted"], res_plot_df["residuals"], s=18, alpha=0.45, color=custom_palette[0], edgecolors="none")
    ax.axhline(0, color=custom_palette[1], linewidth=2.0)
    ax.set_title("Residuals vs fitted values")
    ax.set_xlabel("Fitted values")
    ax.set_ylabel("Residuals")
    plt.tight_layout()
    plot_paths["residuals_vs_fitted"] = save_current_figure(out_dir, "03_residuals_vs_fitted")

    # 4) Residual histogram.
    plt.figure(figsize=(10, 7))
    ax = sns.histplot(residuals, bins=40, kde=True, color=custom_palette[0])
    ax.axvline(0, color=custom_palette[1], linewidth=2.0)
    ax.set_title("Residual distribution")
    ax.set_xlabel("Residual")
    ax.set_ylabel("Count")
    plt.tight_layout()
    plot_paths["residual_histogram"] = save_current_figure(out_dir, "04_residual_histogram")

    # 5) Q-Q plot of residuals.
    plt.figure(figsize=(8, 8))
    ax = plt.gca()
    stats.probplot(residuals, dist="norm", plot=ax)
    ax.get_lines()[0].set_markerfacecolor(custom_palette[0])
    ax.get_lines()[0].set_markeredgecolor(custom_palette[0])
    ax.get_lines()[0].set_alpha(0.45)
    ax.get_lines()[1].set_color(custom_palette[1])
    ax.get_lines()[1].set_linewidth(2.5)
    ax.set_title("Q-Q plot of residuals")
    plt.tight_layout()
    plot_paths["qq_residuals"] = save_current_figure(out_dir, "05_qq_residuals")

    # 6) Observed vs fitted.
    obs_fit_df = pd.DataFrame({"observed": y, "fitted": fitted})
    obs_fit_plot_df = sample_for_plot(obs_fit_df)
    plt.figure(figsize=(8, 8))
    ax = plt.gca()
    ax.scatter(obs_fit_plot_df["fitted"], obs_fit_plot_df["observed"], s=18, alpha=0.45, color=custom_palette[0], edgecolors="none")
    lo = float(min(np.min(y), np.min(fitted)))
    hi = float(max(np.max(y), np.max(fitted)))
    ax.plot([lo, hi], [lo, hi], color=custom_palette[1], linewidth=2.5, label="Ideal: observed = fitted")
    ax.set_title("Observed vs fitted values")
    ax.set_xlabel("Fitted values")
    ax.set_ylabel("Observed values")
    ax.legend()
    plt.tight_layout()
    plot_paths["observed_vs_fitted"] = save_current_figure(out_dir, "06_observed_vs_fitted")

    # 7) Hexbin density.
    plt.figure(figsize=(10, 7))
    ax = plt.gca()
    hb = ax.hexbin(x, y, gridsize=45, mincnt=1, cmap="viridis")
    ax.plot(np.linspace(np.min(x), np.max(x), 200), metrics["intercept"] + metrics["slope"] * np.linspace(np.min(x), np.max(x), 200), color=custom_palette[1], linewidth=2.5)
    cb = plt.colorbar(hb, ax=ax)
    cb.set_label("Count")
    ax.set_title(f"Density view: {feature_1} vs {feature_2}")
    ax.set_xlabel(feature_1)
    ax.set_ylabel(feature_2)
    plt.tight_layout()
    plot_paths["hexbin_density"] = save_current_figure(out_dir, "07_hexbin_density")

    # 8) Rank-rank scatter.
    rank_df = pd.DataFrame({
        "x_rank": pd.Series(x).rank(method="average").to_numpy(),
        "y_rank": pd.Series(y).rank(method="average").to_numpy(),
    })
    rank_plot_df = sample_for_plot(rank_df)
    plt.figure(figsize=(8, 8))
    ax = plt.gca()
    ax.scatter(rank_plot_df["x_rank"], rank_plot_df["y_rank"], s=18, alpha=0.45, color=custom_palette[0], edgecolors="none")
    ax.set_title("Rank-rank relationship")
    ax.set_xlabel(f"Rank({feature_1})")
    ax.set_ylabel(f"Rank({feature_2})")
    plt.tight_layout()
    plot_paths["rank_rank_scatter"] = save_current_figure(out_dir, "08_rank_rank_scatter")

    return plot_paths


def interpret_correlation(value: float) -> str:
    abs_v = abs(value)
    if abs_v < 0.1:
        strength = "negligible"
    elif abs_v < 0.3:
        strength = "weak"
    elif abs_v < 0.5:
        strength = "moderate"
    elif abs_v < 0.7:
        strength = "substantial"
    else:
        strength = "strong"
    direction = "positive" if value > 0 else "negative" if value < 0 else "no"
    return f"{strength} {direction} association"


def write_report(
    path: Path,
    input_csv: Path,
    out_dir: Path,
    feature_1: str,
    feature_2: str,
    x_info: Dict,
    y_info: Dict,
    x_summary: Dict,
    y_summary: Dict,
    corr: Dict,
    fit: Dict,
    bootstrap: Optional[Dict],
    plot_paths: Dict[str, Dict[str, str]],
    samplewise_paths: Dict[str, str],
    rows_raw: int,
    rows_used: int,
) -> None:
    lines: List[str] = []
    lines.append("PAIRWISE CORRELATION ANALYSIS REPORT")
    lines.append("====================================")
    lines.append("")
    lines.append(f"INPUT_CSV: {input_csv.resolve()}")
    lines.append(f"OUTPUT_FOLDER: {out_dir.resolve()}")
    lines.append("")
    lines.append(f"FEATURE_1_X: {feature_1}")
    lines.append(f"FEATURE_2_Y: {feature_2}")
    lines.append(f"ROWS_IN_INPUT: {rows_raw}")
    lines.append(f"ROWS_USED_PAIRWISE_COMPLETE: {rows_used}")
    lines.append(f"ROWS_DROPPED_PAIRWISE: {rows_raw - rows_used}")
    lines.append("")

    lines.append("SAMPLE-BY-SAMPLE HANDLING")
    lines.append("-------------------------")
    lines.append("Yes: the script treats one original CSV row as one sample.")
    lines.append("For every sample, it collects FEATURE_1 raw value, FEATURE_2 raw value, converted x, converted y, and a pairwise_complete flag.")
    lines.append("The statistical analysis uses the pairwise-complete rows only when DROP_MISSING_PAIRWISE=True.")
    lines.append("The sample-wise CSV exports are sorted according to SAMPLEWISE_SORT_BY.")
    if samplewise_paths:
        for key, value in samplewise_paths.items():
            lines.append(f"{key}: {value}")
    else:
        lines.append("Sample-wise table export is disabled.")
    lines.append("")

    lines.append("COLUMN CONVERSION")
    lines.append("-----------------")
    for label, info in [("FEATURE_1_X", x_info), ("FEATURE_2_Y", y_info)]:
        lines.append(f"{label}: {info['column']}")
        lines.append(f"  original_dtype: {info['original_dtype']}")
        lines.append(f"  conversion_kind: {info['conversion_kind']}")
        lines.append(f"  encoding: {info['encoding']}")
        lines.append(f"  raw_missing: {info['num_missing_raw']}")
        lines.append(f"  raw_unique_non_missing: {info['num_unique_raw_non_missing']}")
        if "num_category_levels" in info:
            lines.append(f"  category_levels: {info['num_category_levels']}")
            lines.append("  category_code_mapping_first_levels:")
            for k, v in info.get("category_code_mapping_first_levels", {}).items():
                lines.append(f"    {v}: {k}")
            if info.get("category_mapping_truncated"):
                lines.append(f"  note: {info.get('category_mapping_note')}")
        lines.append("")

    lines.append("NUMERIC SUMMARIES AFTER CONVERSION")
    lines.append("----------------------------------")
    for name, summary in [(feature_1, x_summary), (feature_2, y_summary)]:
        lines.append(name)
        for k, v in summary.items():
            lines.append(f"  {k}: {v}")
        lines.append("")

    lines.append("CORRELATION RESULTS")
    lines.append("-------------------")
    pear = corr["pearson"]
    spear = corr["spearman"]
    kend = corr["kendall"]
    lines.append(f"Pearson r:   {pear['r']:.6f}    p-value: {pear['p_value']:.6g}    interpretation: {interpret_correlation(pear['r'])}")
    lines.append(f"Spearman rho:{spear['rho']:.6f}    p-value: {spear['p_value']:.6g}    interpretation: {interpret_correlation(spear['rho'])}")
    lines.append(f"Kendall tau: {kend['tau']:.6f}    p-value: {kend['p_value']:.6g}    interpretation: {interpret_correlation(kend['tau'])}")
    lines.append("")

    lines.append("LINEAR FIT")
    lines.append("----------")
    lines.append(f"Model: {feature_2} = intercept + slope * {feature_1}")
    lines.append(f"intercept: {fit['intercept']:.10g}")
    lines.append(f"slope: {fit['slope']:.10g}")
    lines.append(f"slope_std_error: {fit['slope_std_error']:.10g}")
    lines.append(f"slope_p_value: {fit['linear_regression_p_value_for_slope']:.6g}")
    lines.append(f"R_squared: {fit['r_squared']:.6f}")
    lines.append(f"adjusted_R_squared: {fit['adjusted_r_squared']:.6f}")
    lines.append(f"RMSE: {fit['rmse']:.10g}")
    lines.append(f"MAE: {fit['mae']:.10g}")
    lines.append(f"residual_standard_error: {fit['residual_standard_error']:.10g}")
    lines.append(f"SSE: {fit['sse']:.10g}")
    lines.append("")

    lines.append("RESIDUAL SUMMARY")
    lines.append("----------------")
    for k in ["residual_mean", "residual_std", "residual_min", "residual_q25", "residual_median", "residual_q75", "residual_max"]:
        lines.append(f"{k}: {fit[k]:.10g}")
    lines.append(f"standardized_residuals_abs_gt_2: {fit['standardized_residuals_abs_gt_2']}")
    lines.append(f"standardized_residuals_abs_gt_3: {fit['standardized_residuals_abs_gt_3']}")
    lines.append("")

    if bootstrap is not None:
        lines.append("BOOTSTRAP CONFIDENCE INTERVALS")
        lines.append("------------------------------")
        lines.append(f"CI level: {bootstrap['ci_level']['value']}")
        for key in ["slope", "intercept", "r_squared"]:
            b = bootstrap[key]
            lines.append(f"{key}: mean={b['mean']:.10g}, low={b['low']:.10g}, high={b['high']:.10g}, successful_iterations={b['n_successful']}")
        lines.append("")

    lines.append("PLOTS WRITTEN")
    lines.append("-------------")
    for plot_name, paths in plot_paths.items():
        lines.append(plot_name)
        for ext, p in paths.items():
            lines.append(f"  {ext}: {p}")
    lines.append("")

    lines.append("INTERPRETATION NOTES")
    lines.append("--------------------")
    lines.append("Pearson measures linear association on the converted numeric values.")
    lines.append("Spearman and Kendall measure monotonic rank association and are less tied to linearity.")
    lines.append("For class columns encoded as 0/1, the linear fit is a descriptive probability-style trend, not a classifier.")
    lines.append("For text/category columns, results depend on the category-code encoding and should be interpreted cautiously.")
    lines.append("Residual plots are used to check whether a straight-line description is adequate.")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if not INPUT_CSV.exists():
        raise SystemExit(f"Input CSV not found: {INPUT_CSV.resolve()}")

    pair_name = f"{safe_name(FEATURE_1)}_vs_{safe_name(FEATURE_2)}_correlation_analysis"
    out_dir = OUTPUT_ROOT / pair_name
    ensure_dir(out_dir)

    df = pd.read_csv(INPUT_CSV, low_memory=False)
    rows_raw = int(len(df))

    adf, samplewise_all, x_info, y_info = prepare_analysis_dataframe(df, FEATURE_1, FEATURE_2)
    rows_used = int(len(adf))

    if rows_used < 3:
        raise SystemExit(
            f"Not enough pairwise complete rows after conversion: {rows_used}. "
            "At least 3 rows are required for correlation and linear regression."
        )

    x = adf["x"].to_numpy(dtype=float)
    y = adf["y"].to_numpy(dtype=float)

    if np.nanstd(x) <= LOW_VARIANCE_EPS:
        raise SystemExit(f"FEATURE_1 has near-zero variance after conversion: {FEATURE_1}")
    if np.nanstd(y) <= LOW_VARIANCE_EPS:
        raise SystemExit(f"FEATURE_2 has near-zero variance after conversion: {FEATURE_2}")

    corr = corr_with_pvalues(x, y)
    fit = linear_fit_metrics(x, y)

    bootstrap = None
    if RUN_BOOTSTRAP:
        bootstrap = bootstrap_linear_ci(
            x=x,
            y=y,
            n_iter=BOOTSTRAP_ITERATIONS,
            ci=BOOTSTRAP_CI,
            random_state=RANDOM_STATE,
        )

    plot_paths = make_plots(adf, out_dir, FEATURE_1, FEATURE_2, fit)

    # Save the pairwise complete analysis data with fitted values, residuals, and row-wise ranks.
    export_df = add_samplewise_diagnostics(adf, fit=fit)
    analysis_csv = out_dir / f"{pair_name}_analysis_data.csv"
    export_df.to_csv(analysis_csv, index=False)

    # Save explicit sample-by-sample tables before/alongside the report.
    samplewise_all_with_ranks = add_samplewise_diagnostics(samplewise_all, fit=None)
    samplewise_paths = save_samplewise_tables(
        out_dir=out_dir,
        pair_name=pair_name,
        samplewise_all=samplewise_all_with_ranks,
        analysis_complete=export_df,
    )

    # TXT report.
    report_path = out_dir / f"{pair_name}_report.txt"
    write_report(
        path=report_path,
        input_csv=INPUT_CSV,
        out_dir=out_dir,
        feature_1=FEATURE_1,
        feature_2=FEATURE_2,
        x_info=x_info,
        y_info=y_info,
        x_summary=basic_summary(x),
        y_summary=basic_summary(y),
        corr=corr,
        fit=fit,
        bootstrap=bootstrap,
        plot_paths=plot_paths,
        samplewise_paths=samplewise_paths,
        rows_raw=rows_raw,
        rows_used=rows_used,
    )

    # JSON summary. Avoid storing full fitted/residual arrays in JSON; those are in analysis CSV.
    fit_json = {k: v for k, v in fit.items() if k not in {"fitted_values", "residuals"}}
    payload = {
        "input_csv": str(INPUT_CSV.resolve()),
        "output_folder": str(out_dir.resolve()),
        "feature_1_x": FEATURE_1,
        "feature_2_y": FEATURE_2,
        "rows_in_input": rows_raw,
        "rows_used_pairwise_complete": rows_used,
        "conversion_feature_1": x_info,
        "conversion_feature_2": y_info,
        "summary_feature_1": basic_summary(x),
        "summary_feature_2": basic_summary(y),
        "correlations": corr,
        "linear_fit": fit_json,
        "bootstrap": bootstrap,
        "analysis_csv": str(analysis_csv.resolve()),
        "samplewise_tables": samplewise_paths,
        "report_txt": str(report_path.resolve()),
        "plots": plot_paths,
        "parameters": {
            "drop_missing_pairwise": DROP_MISSING_PAIRWISE,
            "save_samplewise_tables": SAVE_SAMPLEWISE_TABLES,
            "samplewise_sort_by": SAMPLEWISE_SORT_BY,
            "samplewise_sort_ascending": SAMPLEWISE_SORT_ASCENDING,
            "samplewise_add_rank_columns": SAMPLEWISE_ADD_RANK_COLUMNS,
            "max_points_for_scatter_plots": MAX_POINTS_FOR_SCATTER_PLOTS,
            "n_bins": N_BINS,
            "run_bootstrap": RUN_BOOTSTRAP,
            "bootstrap_iterations": BOOTSTRAP_ITERATIONS,
            "bootstrap_ci": BOOTSTRAP_CI,
            "random_state": RANDOM_STATE,
        },
    }
    json_path = out_dir / f"{pair_name}_summary.json"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    print(f"[OK] Pairwise correlation analysis finished.")
    print(f"[OK] Output folder: {out_dir.resolve()}")
    print(f"[OK] TXT report:    {report_path.resolve()}")
    print(f"[OK] JSON summary:  {json_path.resolve()}")
    print(f"[OK] Analysis CSV:  {analysis_csv.resolve()}")
    for key, value in samplewise_paths.items():
        print(f"[OK] {key}: {value}")


if __name__ == "__main__":
    main()
